:toc: left
:toclevels: 3
:sectnums:
= OpenApi 3 Plugin

//A README.adoc-ot az index.adoc-ból generáljuk preprocessor scripttel, ami kicseréli az include-okat a tényleges adoc szövegre
//mivel a github egyelőre nem képes include-olni csak linkelni
//script: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb script
//futtatás: ruby ~/Work/iCell/Util/asciidoctor/scripts/asciidoc-coalescer.rb -a readme=true -o README.adoc index.adoc
//Releativ linkek megadása:
//ifndef::readme[link:realtiv_utvonal[openapi-demo]]
//ifdef::readme[link:root-utvonal[openapi-demo]]

openapi-jaxb plugin and demo application

== Maven central
This project is available in maven central as:
[source, xml]
----
    <dependency>
        <groupId>hu.icellmobilsoft.jaxb</groupId>
        <artifactId>openapi-jaxb</artifactId>
        <version>1.1.0</version>
    </dependency>
----

:leveloffset: 1

= openapi-jaxb plugin

An extension to the swagger-jaxb XJC plugin.
When generating java code from xsd,
this plugin annotates the generated classes with the proper OpenAPI and/or Swagger annotations (depending on the provided argument).

:leveloffset: 1

= Swagger generation

It uses a https://github.com/peneksglazami/swagger-jaxb[fork] of the https://github.com/redlab/swagger-jaxb[`be.redlab.jaxb:swagger-jaxb`] xjc plugin.
The used fork extends the original plugin with the processing of the `<xs:documentation>` tags.
The fork had been refactored  (https://github.com/icellmobilsoft/swagger-jaxb[`hu.icellmobilsoft.jaxb:swagger-jaxb`])
in order to simplify porting from Swagger to OpenAPI.

The original Swagger compatible genearation is still available with providing the `-swaggerify` argument, see: https://github.com/redlab/swagger-jaxb/blob/master/README.md

:leveloffset!:

:leveloffset: 1

= OpenAPI generation

== Usage

The plugin is activated with the `-openapify` argument.

=== Use with org.jvnet.jaxb2.maven2:maven-jaxb2-plugin maven plugin

[source,xml]
----
...
<plugin>
    <groupId>org.jvnet.jaxb2.maven2</groupId>
    <artifactId>maven-jaxb2-plugin</artifactId>
    <version>0.13.3</version>
    ...
    <configuration>
        <schemaDirectory>src/main/resources</schemaDirectory>
        <schemaIncludes>
            <include>xsd/hu/icellmobilsoft/icon/dto/super.xsd</include>
        </schemaIncludes>
        <generateDirectory>${project.build.directory}/generated-sources/src/main/java</generateDirectory>
        <args>
			<arguments>-openapify</arguments> // <1>
        </args>
        <plugins>
            <plugin> // <2>
				<groupId>hu.icellmobilsoft.jaxb</groupId>
				<artifactId>openapi-jaxb</artifactId>
				<version>1.1.0</version>
            </plugin>

        </plugins>
        <!--<dependencies>--> // <3>
			<!--<dependency>-->
				<!--<groupId>org.eclipse.microprofile.openapi</groupId>-->
				<!--<artifactId>microprofile-openapi-api</artifactId>-->
				<!--<version>1.0.1</version>-->
			<!--</dependency>-->
			<!--<dependency>-->
				<!--<groupId>com.sun.xml.bind</groupId>-->
				<!--<artifactId>jaxb-core</artifactId>-->
				<!--<version>2.2.11</version>-->
			<!--</dependency>-->
        <!--</dependencies>-->
    </configuration>
</plugin>
----
<1> activate the plugin with adding `<arguments>-openapify</arguments>` to `//plugin/configuration/args`.
<2> include the artifact `hu.icellmobilsoft.jaxb:openapi-jaxb` under `//plugin/configuration/plugins`.
<3> The original plugin README states that the transitive dependencies should be provided here, however it work without it..


NOTE: The `-swaggerify` argument is still available, both arguments can be provided, in that case the generated classes will be annotated with both OpenApi and Swagger related annotations.

IMPORTANT: In order to compile the generated sources the `org.eclipse.microprofile.openapi:microprofile-openapi-api`
artifact should be included as dependency (at least with _provided_ scope)!
(This artifact contains the OpenApi annotations)

[source,xml]
----
<project ...>
	...
	<dependencies>
			...
			<dependency>
				<groupId>org.eclipse.microprofile.openapi</groupId>
				<artifactId>microprofile-openapi-api</artifactId>
				<version>1.0.1</version>
				<scope>provided</scope>
			</dependency>
----

== Details

It annotates the classes generated from XSD-s with the `org.eclipse.microprofile.openapi.annotations.media.Schema` annotation.

=== XSD Mapping

[options="header"]
|===
|XSD|Schema

|`//annotation/documentation`|`Schema.description`

|`//complexType/@name`|Class level `Schema.name`

|`//element/@name`|Field level `Schema.name`

|`//element/@maxOccurs`|`Schema.maxLength`

|`//element/@minOccurs`|`Schema.minLength`

|`//simpleType/restriction/minInclusive`|`Schema.minimum` and `Schema.exclusiveMinimum = false`

|`//simpleType/restriction/minExclusive`|`Schema.minimum` and `Schema.exclusiveMinimum = true`

|`//simpleType/restriction/maxInclusive`|`Schema.maximum` and `Schema.exclusiveMaximum = false`

|`//simpleType/restriction/maxExclusive`|`Schema.maximum` and `Schema.exclusiveMaximum = true`

|`//simpleType/restriction/minLength`|`Schema.minLength`

|`//simpleType/restriction/maxLength`|`Schema.maxLength`

|`//simpleType/restriction/length` (Has a higher priority than maxLength,minLength)|`Schema.maxLength` and `Schema.minLength`

|`//simpleType/restriction/pattern`|`Schema.pattern`

|`//simpleType/restriction[@base="xs:string"]/enumeration[n]/@value`|`Schema.enumeration[n]`
|===

=== Verbose description

Some xsd restrictions can not be included into OpenAPI schema definitions, and some OpenAPI implementations doesn't process the `Schema.enumeration`-s properly (or other parameters), furthermore the `<xsd:documentation>`-s provided on the enumeration constants are not generated into the openAPI yaml.
Because of these the plugin can be run with the `verboseDescriptions` flag in order to extended the `description` property with a list of restriction or for enums with the list of possible values and their respective documentation (if any).

==== Setting verbose description with maven-jaxb2-plugin maven plugin

[source,xml]
----
...
<plugin>
    <groupId>org.jvnet.jaxb2.maven2</groupId>
    <artifactId>maven-jaxb2-plugin</artifactId>
    <version>0.13.3</version>
    ...
    <configuration>
        <schemaDirectory>src/main/resources</schemaDirectory>
        <schemaIncludes>
            <include>xsd/hu/icellmobilsoft/icon/dto/super.xsd</include>
        </schemaIncludes>
        <generateDirectory>${project.build.directory}/generated-sources/src/main/java</generateDirectory>
        <args>
			<arguments>-openapify</arguments> // <1>
			<arguments>-openapify:verboseDescriptions</arguments> // <2>
        </args>
        <plugins>
            <plugin>
				<groupId>hu.icellmobilsoft.jaxb</groupId>
				<artifactId>openapi-jaxb</artifactId>
				<version>1.1.0</version>
            </plugin>

        </plugins>
    </configuration>
</plugin>
----
<1> activate the plugin with adding `<arguments>-openapify</arguments>` to `//plugin/configuration/args`.
<2> activate verboseDescription with adding `<arguments>-openapify:verboseDescriptions</arguments>` to `//plugin/configuration/args`.

==== Examples

===== enumeration

====== xsd

[source,xml]
----
    <xs:simpleType name="OperationType">
		<xs:annotation>
			<xs:documentation xml:lang="en">Operation type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="CREATE">
				<xs:annotation>
					<xs:documentation xml:lang="en">Creation exchange</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="MODIFY">
				<xs:annotation>
					<xs:documentation xml:lang="en">Modification exchange</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
----

====== Description

[source,markdown]
----
Operation type

Restrictions:
* Enum:
  * **CREATE** - Creation exchange
  * **MODIFY** - Modification exchange
----

====== Rendered

[.lead]
Operation type

Restrictions:

* Enum:
** **CREATE** - Creation exchange
** **MODIFY** - Modification exchange

===== restricted type

====== xsd

[source,xml]
----
    <xsd:simpleType name="DateType">
        <xsd:restriction base="xsd:date">
            <xsd:minInclusive value="2010-01-01"/>
            <xsd:pattern value="\d{4}-\d{2}-\d{2}"/>
        </xsd:restriction>
    </xsd:simpleType>
----

====== Description

[source,markdown]
----
DateType

Restrictions:
* minimum: 2010-01-01
* exclusiveMinimum: false
* pattern: \d{4}-\d{2}-\d{2}
----

====== Rendered

[.lead]
DateType

Restrictions:

* minimum: 2010-01-01
* exclusiveMinimum: false
* pattern: \d{4}-\d{2}-\d{2}

=== Issues

Known limitations:

* When multiple `documentation` is defined under `//annotation` (ie. multi-language documentation), then only the last one will be processed.
+
ie. from the following xsd only the `text` will be displayed as description
+
[source,xml]
----
<xs:annotation>
    <xs:documentation xml:lang="hu">szöveg</xs:documentation>
    <xs:documentation xml:lang="en">text</xs:documentation>
</xs:annotation>
----

== Example

Poc application:
link:openapi-demo[openapi-demo]



:leveloffset!:

:leveloffset!:

:leveloffset: 1

= OpenApi POC
:demoVersion: 1.1.1-SNAPSHOT
:thorntailJar: openapi-demo-service/target/openapi-demo-service-{demoVersion}-thorntail.jar

POC application for openApi plugin

== Modules

:leveloffset: 2

= OpenApi Demo DTO

DTO module for openApi demo.
A sample xsd is used to define the business objects,
XJC is used with the `openapi-jaxb` plugin to process the xsd and
generate the java representations annotated with OpenAPI annotations.

link:openapi-demo/openapi-demo-dto/src/main/resources/xsd/hu/icellmobilsoft/jaxb/openapi/dto/sample.xsd[]

:leveloffset!:

:leveloffset: 2

= OpenApi Demo service

REST endpoint (`/sample/xsd`) which consumes and provides the `SampleType` object
generated by xjc from the definition provided in the `sample.xsd` (in dto module).

Since `io.thorntail:microprofile-openapi` is bundled, the OpenAPI 3 yaml is available under `/openapi`.

:leveloffset!:

== Running the POC

. `[openapi-demo]$ mvn clean install`
. `[openapi-demo]$ java -jar {thorntailJar}`

After startup the OpenApi yaml is available under `localhost:8080/openapi`.

== Generated examples

=== Normal run
* link:openapi-demo/generated/openapi.yaml[OpenAPI 3.0 YAML]
* link:openapi-demo/generated/openapi.html[HTML generated from OpenAPI yaml with redoc]

=== With verboseDescriptions switch
* link:openapi-demo/generated/openapi-verboseDescriptions.yaml[OpenAPI 3.0 YAML (verboseDescriptions)]
* link:openapi-demo/generated/openapi-verboseDescriptions.html[HTML generated from OpenAPI yaml with redoc (verboseDescriptions]

:leveloffset!: