= OpenAPI generation

== Usage

The plugin is activated with the `-openapify` argument.

=== Use with org.jvnet.jaxb2.maven2:maven-jaxb2-plugin maven plugin

[source,xml]
----
...
<plugin>
    <groupId>org.jvnet.jaxb2.maven2</groupId>
    <artifactId>maven-jaxb2-plugin</artifactId>
    <version>0.13.3</version>
    ...
    <configuration>
        <schemaDirectory>src/main/resources</schemaDirectory>
        <schemaIncludes>
            <include>xsd/hu/icellmobilsoft/icon/dto/super.xsd</include>
        </schemaIncludes>
        <generateDirectory>${project.build.directory}/generated-sources/src/main/java</generateDirectory>
        <args>
			<arguments>-openapify</arguments> // <1>
        </args>
        <plugins>
            <plugin> // <2>
				<groupId>hu.icellmobilsoft.jaxb</groupId>
				<artifactId>openapi-jaxb</artifactId>
				<version>1.1.0</version>
            </plugin>

        </plugins>
        <!--<dependencies>--> // <3>
			<!--<dependency>-->
				<!--<groupId>org.eclipse.microprofile.openapi</groupId>-->
				<!--<artifactId>microprofile-openapi-api</artifactId>-->
				<!--<version>1.0.1</version>-->
			<!--</dependency>-->
			<!--<dependency>-->
				<!--<groupId>com.sun.xml.bind</groupId>-->
				<!--<artifactId>jaxb-core</artifactId>-->
				<!--<version>2.2.11</version>-->
			<!--</dependency>-->
        <!--</dependencies>-->
    </configuration>
</plugin>
----
<1> activate the plugin with adding `<arguments>-openapify</arguments>` to `//plugin/configuration/args`.
<2> include the artifact `hu.icellmobilsoft.jaxb:openapi-jaxb` under `//plugin/configuration/plugins`.
<3> The original plugin README states that the transitive dependencies should be provided here, however it work without it..


NOTE: The `-swaggerify` argument is still available, both arguments can be provided, in that case the generated classes will be annotated with both OpenApi and Swagger related annotations.

IMPORTANT: In order to compile the generated sources the `org.eclipse.microprofile.openapi:microprofile-openapi-api`
artifact should be included as dependency (at least with _provided_ scope)!
(This artifact contains the OpenApi annotations)

[source,xml]
----
<project ...>
	...
	<dependencies>
			...
			<dependency>
				<groupId>org.eclipse.microprofile.openapi</groupId>
				<artifactId>microprofile-openapi-api</artifactId>
				<version>1.0.1</version>
				<scope>provided</scope>
			</dependency>
----

== Details

It annotates the classes generated from XSD-s with the `org.eclipse.microprofile.openapi.annotations.media.Schema` annotation.

=== XSD Mapping

[options="header"]
|===
|XSD|Schema

|`//annotation/documentation`|`Schema.description`

|`//complexType/@name`|Class level `Schema.name`

|`//element/@name`|Field level `Schema.name`

|`//element/@maxOccurs`|`Schema.maxLength`

|`//element/@minOccurs`|`Schema.minLength`

|`//simpleType/restriction/minInclusive`|`Schema.minimum` and `Schema.exclusiveMinimum = false`

|`//simpleType/restriction/minExclusive`|`Schema.minimum` and `Schema.exclusiveMinimum = true`

|`//simpleType/restriction/maxInclusive`|`Schema.maximum` and `Schema.exclusiveMaximum = false`

|`//simpleType/restriction/maxExclusive`|`Schema.maximum` and `Schema.exclusiveMaximum = true`

|`//simpleType/restriction/minLength`|`Schema.minLength`

|`//simpleType/restriction/maxLength`|`Schema.maxLength`

|`//simpleType/restriction/length` (Has a higher priority than maxLength,minLength)|`Schema.maxLength` and `Schema.minLength`

|`//simpleType/restriction/pattern`|`Schema.pattern`

|`//simpleType/restriction[@base="xs:string"]/enumeration[n]/@value`|`Schema.enumeration[n]`
|===

=== Verbose description

Some xsd restrictions can not be included into OpenAPI schema definitions, and some OpenAPI implementations doesn't process the `Schema.enumeration`-s properly (or other parameters), furthermore the `<xsd:documentation>`-s provided on the enumeration constants are not generated into the openAPI yaml.
Because of these the plugin can be run with the `verboseDescriptions` flag in order to extended the `description` property with a list of restriction or for enums with the list of possible values and their respective documentation (if any).

==== Setting verbose description with maven-jaxb2-plugin maven plugin

[source,xml]
----
...
<plugin>
    <groupId>org.jvnet.jaxb2.maven2</groupId>
    <artifactId>maven-jaxb2-plugin</artifactId>
    <version>0.13.3</version>
    ...
    <configuration>
        <schemaDirectory>src/main/resources</schemaDirectory>
        <schemaIncludes>
            <include>xsd/hu/icellmobilsoft/icon/dto/super.xsd</include>
        </schemaIncludes>
        <generateDirectory>${project.build.directory}/generated-sources/src/main/java</generateDirectory>
        <args>
			<arguments>-openapify</arguments> // <1>
			<arguments>-openapify:verboseDescriptions</arguments> // <2>
        </args>
        <plugins>
            <plugin>
				<groupId>hu.icellmobilsoft.jaxb</groupId>
				<artifactId>openapi-jaxb</artifactId>
				<version>1.1.0</version>
            </plugin>

        </plugins>
    </configuration>
</plugin>
----
<1> activate the plugin with adding `<arguments>-openapify</arguments>` to `//plugin/configuration/args`.
<2> activate verboseDescription with adding `<arguments>-openapify:verboseDescriptions</arguments>` to `//plugin/configuration/args`.

==== Examples

===== enumeration

====== xsd

[source,xml]
----
    <xs:simpleType name="OperationType">
		<xs:annotation>
			<xs:documentation xml:lang="en">Operation type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="CREATE">
				<xs:annotation>
					<xs:documentation xml:lang="en">Creation exchange</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="MODIFY">
				<xs:annotation>
					<xs:documentation xml:lang="en">Modification exchange</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
----

====== Description

[source,markdown]
----
Operation type

Restrictions:
* Enum:
  * **CREATE** - Creation exchange
  * **MODIFY** - Modification exchange
----

====== Rendered

[.lead]
Operation type

Restrictions:

* Enum:
** **CREATE** - Creation exchange
** **MODIFY** - Modification exchange

===== restricted type

====== xsd

[source,xml]
----
    <xsd:simpleType name="DateType">
        <xsd:restriction base="xsd:date">
            <xsd:minInclusive value="2010-01-01"/>
            <xsd:pattern value="\d{4}-\d{2}-\d{2}"/>
        </xsd:restriction>
    </xsd:simpleType>
----

====== Description

[source,markdown]
----
DateType

Restrictions:
* minimum: 2010-01-01
* exclusiveMinimum: false
* pattern: \d{4}-\d{2}-\d{2}
----

====== Rendered

[.lead]
DateType

Restrictions:

* minimum: 2010-01-01
* exclusiveMinimum: false
* pattern: \d{4}-\d{2}-\d{2}

=== Issues

Known limitations:

* When multiple `documentation` is defined under `//annotation` (ie. multi-language documentation), then only the last one will be processed.
+
ie. from the following xsd only the `text` will be displayed as description
+
[source,xml]
----
<xs:annotation>
    <xs:documentation xml:lang="hu">szöveg</xs:documentation>
    <xs:documentation xml:lang="en">text</xs:documentation>
</xs:annotation>
----

== Example

Poc application:
ifndef::readme[link:../../openapi-demo[openapi-demo]]
ifdef::readme[link:openapi-demo[openapi-demo]]


