= OpenAPI generation

== Usage

The plugin is activated with the `-openapify` argument.

=== Configuration arguments

The following configuration options can be used via xjc arguments

|===
|Activation argument |Description

|-openapify:verboseDescriptions
|Schema descriptions will be more detailed when activated. See <<verbose-descriptions>>

|-openapify:preferJavaName
|For java fields the schema name will be the same as the java field name when activated instead of the actual xsd element name. See <<preferJavaName>>

|-openapify:skipExtensions
|Do not generate `extensions` on `@Schema` fields. See <<schema-extensions>>

|===


[#openapi-usage]
=== Use with maven plugin

The plugin requires XJC from jaxb 4.0,
a viable solution is using the https://github.com/phax/maven-jaxb2-plugin/tree/v016[phax/maven-jaxb2-plugin] jaxb 4.0 maven plugin fork.

[source,xml]
----
<!-- ... -->
<plugin>
    <groupId>com.helger.maven</groupId>
    <artifactId>jaxb40-maven-plugin</artifactId>
    <version>0.16.0</version>
    <!-- ... -->
    <configuration>
        <schemaDirectory>src/main/resources</schemaDirectory>
        <schemaIncludes>
            <include>xsd/hu/icellmobilsoft/icon/dto/super.xsd</include>
        </schemaIncludes>
        <generateDirectory>${project.build.directory}/generated-sources/src/main/java</generateDirectory>
        <args>
			<arguments>-openapify</arguments> <!--1-->
        </args>
        <plugins>
            <plugin> <!--2-->
				<groupId>hu.icellmobilsoft.jaxb</groupId>
				<artifactId>openapi-jaxb-plugin</artifactId>
				<version>${openapi-jaxb-plugin.version}</version>
            </plugin>
        </plugins>
    </configuration>
</plugin>
----
<1> activate the plugin with adding `<arguments>-openapify</arguments>` to `//plugin/configuration/args`.
<2> include the artifact `hu.icellmobilsoft.jaxb:openapi-jaxb` under `//plugin/configuration/plugins`.


IMPORTANT: In order to compile the generated sources the `org.eclipse.microprofile.openapi:microprofile-openapi-api`
artifact should be included as dependency (at least with _provided_ scope)!
(This artifact contains the OpenApi annotations)

[source,xml]
----
	<!-- ... -->
	<dependencies>
			<!-- ... -->
			<dependency>
				<groupId>org.eclipse.microprofile.openapi</groupId>
				<artifactId>microprofile-openapi-api</artifactId>
				<version>${microprofile-openapi-api.version}</version>
				<scope>provided</scope>
			</dependency>
            <!-- ... -->
	</dependencies>
----

== Details

It annotates the classes generated from XSD-s with the `org.eclipse.microprofile.openapi.annotations.media.Schema` annotation.

=== XSD Mapping

[options="header"]
|===
|XSD|Schema

|`//annotation/documentation`|`Schema.description`

|`//complexType/@name`|Class level `Schema.name`

|`//element/@name`|Field level `Schema.name`

|`//element/@maxOccurs`|`Schema.maxLength`

|`//element/@minOccurs`|`Schema.minLength`

|`//simpleType/restriction/minInclusive`|`Schema.minimum` and `Schema.exclusiveMinimum = false`

|`//simpleType/restriction/minExclusive`|`Schema.minimum` and `Schema.exclusiveMinimum = true`

|`//simpleType/restriction/maxInclusive`|`Schema.maximum` and `Schema.exclusiveMaximum = false`

|`//simpleType/restriction/maxExclusive`|`Schema.maximum` and `Schema.exclusiveMaximum = true`

|`//simpleType/restriction/minLength`|`Schema.minLength`

|`//simpleType/restriction/maxLength`|`Schema.maxLength`

|`//simpleType/restriction/length` (Has a higher priority than maxLength,minLength)|`Schema.maxLength` and `Schema.minLength`

|`//simpleType/restriction/pattern`|`Schema.pattern`

|`//simpleType/restriction[@base="xs:string"]/enumeration[n]/@value`|`Schema.enumeration[n]`
|===

[#verbose-descriptions]
=== Verbose descriptions

Some xsd restrictions can not be included into OpenAPI schema definitions, and some OpenAPI implementations doesn't process the `Schema.enumeration`-s properly (or other parameters), furthermore the `<xsd:documentation>`-s provided on the enumeration constants are not generated into the openAPI yaml.
Because of these the plugin can be run with the `verboseDescriptions` flag in order to extended the `description` property with a list of restriction or for enums with the list of possible values and their respective documentation (if any).

==== Setting verbose description with maven plugin

[source,xml]
----
<!-- ... -->
<plugin>
    <groupId>com.helger.maven</groupId>
    <artifactId>jaxb40-maven-plugin</artifactId>
    <version>0.16.0</version>
    <!-- ... -->
    <configuration>
        <args>
			<arguments>-openapify</arguments><!--1-->
			<arguments>-openapify:verboseDescriptions</arguments><!--2-->
        </args>
        <plugins>
            <plugin>
				<groupId>hu.icellmobilsoft.jaxb</groupId>
				<artifactId>openapi-jaxb-plugin</artifactId>
				<version>${openapi-jaxb-plugin.version}</version>
            </plugin>
        </plugins>
    </configuration>
</plugin>
----
<1> activate the plugin with adding `<arguments>-openapify</arguments>` to `//plugin/configuration/args`.
<2> activate verboseDescription with adding `<arguments>-openapify:verboseDescriptions</arguments>` to `//plugin/configuration/args`.

==== Examples

===== enumeration

====== xsd

[source,xml]
----
    <xs:simpleType name="OperationType">
		<xs:annotation>
			<xs:documentation xml:lang="en">Operation type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="CREATE">
				<xs:annotation>
					<xs:documentation xml:lang="en">Creation exchange</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="MODIFY">
				<xs:annotation>
					<xs:documentation xml:lang="en">Modification exchange</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
----

====== Description

[source,markdown]
----
Operation type

Restrictions:
* Enum:
  * **CREATE** - Creation exchange
  * **MODIFY** - Modification exchange
----

====== Rendered

[.lead]
Operation type

Restrictions:

* Enum:
** **CREATE** - Creation exchange
** **MODIFY** - Modification exchange

===== restricted type

====== xsd

[source,xml]
----
    <xsd:simpleType name="DateType">
        <xsd:restriction base="xsd:date">
            <xsd:minInclusive value="2010-01-01"/>
            <xsd:pattern value="\d{4}-\d{2}-\d{2}"/>
        </xsd:restriction>
    </xsd:simpleType>
----

====== Description

[source,markdown]
----
DateType

Restrictions:
* minimum: 2010-01-01
* exclusiveMinimum: false
* pattern: \d{4}-\d{2}-\d{2}
----

====== Rendered

[.lead]
DateType

Restrictions:

* minimum: 2010-01-01
* exclusiveMinimum: false
* pattern: +\d{4}-\d{2}-\d{2}+

[#preferJavaName]
=== Java vs. XSD names

In most cases the java field name will be the same as the xsd element name,
but i.e. if the name is reserved in java xjc will generate different field name.

.SampleType xsd definition
[source, xml]
----
<xs:complexType name="SampleType">
        <xs:sequence>
            <xs:element name="case" type="xs:string"/>
        </xs:sequence>
</xs:complexType>
----

.SampleType generated java code
[source, java]
----
public class SampleType {
    @Schema(name = "case")
    @XmlElement(name = "case")
    protected String _case;
}
----

By default the plugin will follow the xsd declaration and the `_case` field will have the
`@Schema(name = "case")` annotation.

This behaviour can be changed activating the *-openapify:preferJavaName* argument, in which case the schema name will be
the same as the java field name, the annotaion will be `@Schema(name = "_case")`.

.SampleType generated java code with `-openapify:preferJavaName` argument
[source, java]
----
public class SampleType {
    @Schema(name = "_case")
    @XmlElement(name = "case")
    protected String _case;
}
----

[#schema-extensions]
=== XML specific setting with schema Extensions

The OpenAPI spec allows fine-tuning properties for
https://github.com/eclipse/microprofile-open-api/blob/3.1/api/src/main/java/org/eclipse/microprofile/openapi/models/media/XML.java[XML].

The plugin can generate the following properties as `@Extensions`


|===
|Property |Description |Generated extension key

|name|XML name (can differ from json name)|`x-xml-name`
|namespace|XML namespace|`x-xml-namespace`
|prefix|XML namespace prefix|`x-xml-prefix`
|attribute|Indicates that field is xml attribute not element|`x-xml-attribute`
|===

.Extension example
[source, java]
----
@Schema(name = "SampleType", extensions = {
    @Extension(name = "x-xml-namespace", value = "http://sample.dto.openapi.icellmobilsoft.hu/sample")
})
public class SampleType {

    @Schema(name = "attributeName", extensions = {
            @Extension(name = "x-xml-attribute", value = "true", parseValue = true)
    })
    protected String attributeName;
}
----

The https://swagger.io/docs/specification/data-models/representing-xml/[OpenAPI specification]
allows the properties above to be declared.
In Microprofile 6.0 the `@Schema` annotation does not support it directly,
but the `Schema` interface does.
The `XmlExtensionUtil` or the `XmlExtensionOpenAPIFilter` in `openapi-jaxb-tool` module can be used to replace
the extensions above with the correct `xml` fields.

The extension generation can be turned off with `-openapify:skipExtensions` attribute.

=== Issues

Known limitations:

* When multiple `documentation` is defined under `//annotation` (ie. multi-language documentation), then only the last one will be processed.
+
ie. from the following xsd only the `text` will be displayed as description
+
[source,xml]
----
<xs:annotation>
    <xs:documentation xml:lang="hu">szöveg</xs:documentation>
    <xs:documentation xml:lang="en">text</xs:documentation>
</xs:annotation>
----


